#!/usr/bin/env python
"""Set up and verify a SAS connection, interactively.

The companion to ``sas_probe.py``: the probe *diagnoses* a connection, this one
*creates* it. It asks for what it needs, writes the config saspy expects,
verifies it end to end, and leaves behind a reusable profile.

    python scripts/sas_setup.py                 # interactive wizard
    python scripts/sas_setup.py --verify        # re-test the saved profile
    python scripts/sas_setup.py --show          # print the config it would use
    python scripts/sas_setup.py --non-interactive --host sas.corp --user me

Profiles live in ``~/.dqc/sas_profiles.json`` and the generated saspy config in
``~/.dqc/sascfg_personal.py``. Passwords are never written to either: they are
read from the ``SAS_PASSWORD`` environment variable or prompted for each run.
"""

from __future__ import annotations

import argparse
import getpass
import json
import os
import shutil
import socket
import stat
import subprocess
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

CONFIG_DIR = Path(os.getenv("DQC_SAS_HOME", Path.home() / ".dqc"))
PROFILES = CONFIG_DIR / "sas_profiles.json"
SASCFG = CONFIG_DIR / "sascfg_personal.py"


@dataclass
class Profile:
    name: str = "default"
    mode: str = "iom"                 # iom | viya
    host: str = ""
    port: int = 8591
    user: str = ""
    table: str = "mylib.ciclos_recuperacion"
    viya_url: str = ""
    java: str = ""
    classpath: str = ""
    encoding: str = "latin1"          # SAS 9.4 default on Windows/Linux deploys
    # Never stored: password, token.

    def to_dict(self) -> dict:
        return asdict(self)


# ── config I/O ────────────────────────────────────────────────────────────

def harden_file(path: Path) -> bool:
    """Restrict a file to its owner. Returns False when that could not be done.

    ``os.chmod`` on Windows only toggles the read-only bit — it does not remove
    other principals — so the POSIX call is followed by icacls there. Nothing
    secret is stored in these files, but the host and account are worth not
    leaving world-readable.
    """
    try:
        path.chmod(stat.S_IRUSR | stat.S_IWUSR)      # 0600 (POSIX)
    except OSError:
        pass
    if sys.platform != "win32":
        try:
            return path.stat().st_mode & 0o077 == 0
        except OSError:
            return False
    user = os.environ.get("USERNAME") or os.environ.get("USER") or ""
    if not user:
        return False
    try:
        done = subprocess.run(
            ["icacls", str(path), "/inheritance:r", "/grant:r", f"{user}:F"],
            capture_output=True, text=True, timeout=30)
        return done.returncode == 0
    except (OSError, subprocess.SubprocessError):
        return False


def load_profiles() -> dict[str, dict]:
    if not PROFILES.exists():
        return {}
    try:
        return json.loads(PROFILES.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        print(f"  ! {PROFILES} is not valid JSON; ignoring it.", file=sys.stderr)
        return {}


def save_profile(profile: Profile) -> None:
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    data = load_profiles()
    data[profile.name] = profile.to_dict()
    PROFILES.write_text(json.dumps(data, indent=2), encoding="utf-8")
    if not harden_file(PROFILES):
        print(f"  ! could not restrict permissions on {PROFILES} — "
              f"check who can read it")
    print(f"  profile '{profile.name}' → {PROFILES}")


def write_sascfg(profile: Profile) -> Path:
    """Generate the sascfg_personal.py saspy looks for.

    saspy is configured by a Python module, not a dotfile, which is why this
    is generated rather than templated into JSON.
    """
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    java = profile.java or shutil.which("java") or "java"
    cp = profile.classpath or "<path to sas.core.jar:sas.security.sspi.jar>"
    # repr(), never bare interpolation: a Windows path in a Python string
    # literal is at best corrupted (C:\\temp -> TAB) and at worst a
    # SyntaxError (C:\\Users -> truncated \\UXXXXXXXX escape), and
    # C:\\Users is exactly where saspy's own jar lives.
    body = (
        '"""Generated by scripts/sas_setup.py — edit the profile, not this file."""\n\n'
        f"SAS_config_names = [{profile.name!r}]\n\n"
        f"{profile.name} = {{\n"
        f"    'java': {java!r},\n"
        f"    'iomhost': {profile.host!r},\n"
        f"    'iomport': {int(profile.port)!r},\n"
        f"    'encoding': {profile.encoding!r},\n"
        f"    'classpath': {cp!r},\n"
        "}\n"
    )
    SASCFG.write_text(body, encoding="utf-8")
    harden_file(SASCFG)
    return SASCFG


# ── checks ────────────────────────────────────────────────────────────────

# saspy's IOM client talks to SAS 9.4-era jars (log4j 1.2.x, sas.core 9.4).
# A current JDK is the wrong choice here: distro "jre-openjdk" is Java 26 on
# Arch today, and the old jars are not tested against it. 11 is the safe
# default, 8 the fallback when IOM complains.
JRE_TARGET = "11"


def jre_install_hint() -> str:
    """The command that actually works on THIS machine."""
    if shutil.which("mise"):
        return (f"mise use -g java@temurin-{JRE_TARGET}"
                f"   (no sudo; mise is already on this machine)")
    if shutil.which("pacman"):
        return (f"sudo pacman -S jre{JRE_TARGET}-openjdk"
                f"   (NOT 'jre-openjdk' — that is Java 26, too new for SAS 9.4)")
    if shutil.which("apt"):
        return f"sudo apt install openjdk-{JRE_TARGET}-jre-headless"
    if shutil.which("dnf"):
        return f"sudo dnf install java-{JRE_TARGET}-openjdk-headless"
    if shutil.which("brew"):
        return f"brew install --cask temurin@{JRE_TARGET}"
    if sys.platform == "win32":
        return (f"winget install EclipseAdoptium.Temurin.{JRE_TARGET}.JRE"
                f"   (or download from adoptium.net)")
    return f"install a Java {JRE_TARGET} runtime (adoptium.net)"


def java_version() -> str:
    """Reported version of the java on PATH, or '' if none."""
    exe = shutil.which("java")
    if not exe:
        return ""
    try:
        out = subprocess.run([exe, "-version"], capture_output=True, text=True,
                             timeout=15)
        line = (out.stderr or out.stdout or "").splitlines()
        return line[0].strip() if line else ""
    except Exception:  # noqa: BLE001
        return ""


def session_context() -> dict:
    """Where is this Python actually running?

    Decisive for SAS access. A published Citrix/RDP app or desktop is a
    *remote* session: the IOM port is reachable from the session host, not from
    the workstation that launched it. Code running on the laptop cannot reach a
    server that only the Citrix farm can see, however well saspy is configured,
    so knowing which side of the gateway you are on comes before any
    connection tuning.

    Citrix and RDP both set SESSIONNAME (ICA-* for Citrix, RDP-* for RDP) and
    CLIENTNAME (the launching device).
    """
    env = os.environ
    session = env.get("SESSIONNAME", "")
    client = env.get("CLIENTNAME", "")
    kind = "local"
    if session.upper().startswith("ICA") or env.get("CITRIX_SESSION"):
        kind = "citrix"
    elif session.upper().startswith("RDP"):
        kind = "rdp"
    elif client and client.upper() != "CONSOLE":
        kind = "remote"
    return {
        "kind": kind,
        "sessionname": session,
        "clientname": client,
        "host": socket.gethostname(),
        "platform": sys.platform,
    }


def check_dependencies(mode: str) -> list[str]:
    """Missing prerequisites, as actionable install lines."""
    missing: list[str] = []
    if mode == "viya":
        try:
            import httpx  # noqa: F401
        except ImportError:
            missing.append("pip install httpx")
        return missing
    try:
        import saspy  # noqa: F401
    except ImportError:
        missing.append("pip install saspy")
    if not shutil.which("java"):
        missing.append(f"install a JRE — saspy's IOM access runs over Java:\n"
                       f"      {jre_install_hint()}")
    else:
        ver = java_version()
        major = ""
        import re as _re
        m = _re.search(r'"(\d+)(?:\.(\d+))?', ver)
        if m:
            major = m.group(2) if m.group(1) == "1" else m.group(1)
        if major.isdigit() and int(major) > 17:
            missing.append(
                f"Java {major} is newer than SAS 9.4's IOM jars are tested "
                f"against ({ver}).\n"
                f"      If the session fails to start, install Java "
                f"{JRE_TARGET}:\n      {jre_install_hint()}")
    return missing


# saspy's IOM access method runs over Java and needs five jars. Four ship with
# a SAS *client* installation; the fifth ships with saspy itself.
SAS_JARS = ("sas.core", "sas.security.sspi", "sas.svc.connection", "log4j")
SASPY_JAR = "saspyiom"

# In a real SASHome these are versioned — sas.core_904400.0.0.<build>.jar — so
# searching for the bare "sas.core.jar" finds nothing. Glob the stem instead.
def _sas_roots() -> tuple[Path, ...]:
    """Where a SAS client installation usually lives.

    On Windows SASHome is frequently not on C: — site installs put it on a
    dedicated drive — so every mounted drive letter is checked. Probing a
    non-existent drive is a cheap stat, not a scan.
    """
    roots = [Path("/opt/sas"), Path("/opt/SASHome"), Path("/usr/local/SASHome"),
             Path.home() / "sas", Path.home() / "SASHome"]
    if sys.platform == "win32":
        import string
        for drive in string.ascii_uppercase:
            for name in ("SASHome", "Program Files/SASHome",
                         "Program Files (x86)/SASHome"):
                roots.append(Path(f"{drive}:/{name}"))
    else:
        roots += [Path("C:/Program Files/SASHome"),
                  Path("C:/Program Files (x86)/SASHome"), Path("C:/SASHome")]
    return tuple(roots)


SAS_ROOTS = _sas_roots()


def find_saspy_jar_dir() -> Path | None:
    """saspyiom.jar lives inside the installed saspy package, not in SASHome."""
    try:
        import saspy
    except ImportError:
        return None
    candidate = Path(saspy.__file__).parent / "java"
    return candidate if candidate.is_dir() else None


def find_sas_jars(extra_roots: tuple[Path, ...] = ()) -> dict[str, str]:
    """Locate each required jar. Returns {stem: path}; missing stems are absent.

    Searches the SAS install roots for versioned names, and the installed
    saspy package for saspyiom.jar.
    """
    found: dict[str, str] = {}
    for root in tuple(extra_roots) + SAS_ROOTS:
        if not root.exists():
            continue
        for stem in SAS_JARS:
            if stem in found:
                continue
            for pattern in (f"{stem}.jar", f"{stem}_*.jar", f"{stem}-*.jar"):
                hit = next(iter(sorted(root.rglob(pattern))), None)
                if hit:
                    found[stem] = str(hit)
                    break

    jar_dir = find_saspy_jar_dir()
    if jar_dir:
        hit = next(iter(sorted(jar_dir.glob(f"{SASPY_JAR}*.jar"))), None)
        if hit:
            found[SASPY_JAR] = str(hit)
        # saspy also bundles copies of the SAS jars for some deployments.
        for stem in SAS_JARS:
            if stem not in found:
                hit = next(iter(sorted(jar_dir.glob(f"{stem}*.jar"))), None)
                if hit:
                    found[stem] = str(hit)
    return found


def build_classpath(found: dict[str, str]) -> str:
    """Explicit jar paths joined with the platform separator.

    Explicit rather than a `dir/*` wildcard: the jars are usually spread across
    several directories, and a wildcard would also drag in every other jar in
    SASVersionedJarRepository.
    """
    return os.pathsep.join(found[stem] for stem in
                           (*SAS_JARS, SASPY_JAR) if stem in found)


def report_jars(found: dict[str, str]) -> list[str]:
    """Which required jars are still missing, with where to get them."""
    missing = [s for s in (*SAS_JARS, SASPY_JAR) if s not in found]
    lines = []
    for stem in missing:
        if stem == SASPY_JAR:
            lines.append(f"{stem}.jar — ships with saspy; run `pip install saspy`")
        else:
            lines.append(f"{stem}.jar — from a SAS client installation "
                         f"(look under SASHome/SASVersionedJarRepository)")
    return lines


# ── wizard ────────────────────────────────────────────────────────────────

def ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    if not sys.stdin.isatty():          # piped or redirected: take the default
        return default
    try:
        answer = input(f"  {prompt}{suffix}: ").strip()
    except (EOFError, KeyboardInterrupt):
        return default
    return answer or default


def wizard(existing: Profile) -> Profile:
    print("\n── SAS connection setup ──────────────────────────────────────")
    print("  Nothing is sent until the end, and no password is written to disk.\n")

    ctx = session_context()
    print(f"  Running on {ctx['host']} ({ctx['platform']}), session: {ctx['kind']}")
    if ctx["kind"] == "local" and ctx["platform"] == "win32":
        print("  Note: this is a local Windows session. If SAS is only published")
        print("  through Citrix, the IOM port is reachable from the Citrix session")
        print("  host, not from here — see docs/SAS_CONNECTIVITY.md.")
    elif ctx["kind"] in ("citrix", "rdp"):
        print(f"  Inside a {ctx['kind']} session (launched from "
              f"{ctx['clientname'] or 'unknown'}) — a direct IOM connection is "
              f"plausible from here.")
    print()

    mode = ask("Mode: (1) SAS 9.4 workspace server via IOM  (2) SAS Viya REST",
               "1" if existing.mode == "iom" else "2")
    p = Profile(name=existing.name, mode="viya" if mode.strip() == "2" else "iom")

    p.name = ask("Profile name", existing.name or "default")
    if p.mode == "viya":
        p.viya_url = ask("Viya base URL (https://...)", existing.viya_url)
    else:
        p.host = ask("Workspace server host", existing.host)
        p.port = int(ask("IOM port", str(existing.port or 8591)) or 8591)
        p.user = ask("User", existing.user or os.getenv("USER", ""))
        p.encoding = ask("SAS session encoding", existing.encoding or "latin1")

        found = find_sas_jars()
        if found:
            print("\n  Found:")
            for stem, path in found.items():
                print(f"    {stem + '.jar':<26} {path}")
        missing = report_jars(found)
        if missing:
            print("\n  ! Missing jars — saspy's IOM access cannot connect without them:")
            for line in missing:
                print(f"    {line}")
            print("\n    They are not on PyPI (except saspyiom.jar). In a SASHome they")
            print("    are versioned, e.g. sas.core_904400.0.0.<build>.jar, so searching")
            print("    for the bare name finds nothing:")
            print("      find /opt/sas -name 'sas.core*.jar'")
        default_cp = build_classpath(found) or existing.classpath
        p.classpath = ask("Java classpath for the SAS jars", default_cp)

    p.table = ask("A table to test a 1-row SELECT against", existing.table)
    return p


# ── verification ──────────────────────────────────────────────────────────

def verify(profile: Profile, password: str = "") -> int:
    """Run sas_probe against this profile and report."""
    cmd = [sys.executable, str(Path(__file__).parent / "sas_probe.py"),
           "--table", profile.table]
    if profile.mode == "viya":
        cmd += ["--viya", profile.viya_url]
        token = os.getenv("SAS_TOKEN", "")
        if token:
            cmd += ["--token", token]
    else:
        cmd += ["--host", profile.host, "--port", str(profile.port)]
        if profile.user:
            cmd += ["--user", profile.user]
        if profile.name:
            cmd += ["--cfgname", profile.name]

    env = dict(os.environ)
    if password:
        env["SAS_PASSWORD"] = password
    if SASCFG.exists():
        # saspy imports sascfg_personal from sys.path
        env["PYTHONPATH"] = f"{CONFIG_DIR}{os.pathsep}{env.get('PYTHONPATH', '')}"

    print(f"\n  running: {' '.join(cmd[1:])}\n")
    return subprocess.call(cmd, env=env)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--profile", default="default")
    ap.add_argument("--verify", action="store_true",
                    help="re-test the saved profile without reconfiguring")
    ap.add_argument("--show", action="store_true",
                    help="print the saved profile and generated saspy config")
    ap.add_argument("--non-interactive", action="store_true")
    ap.add_argument("--host"); ap.add_argument("--port", type=int, default=8591)
    ap.add_argument("--user"); ap.add_argument("--viya"); ap.add_argument("--table")
    args = ap.parse_args()

    saved = load_profiles().get(args.profile, {})
    profile = Profile(**{**Profile(name=args.profile).to_dict(), **saved})

    if args.show:
        print(json.dumps(profile.to_dict(), indent=2))
        if SASCFG.exists():
            print(f"\n── {SASCFG} ──")
            print(SASCFG.read_text(encoding="utf-8"))
        else:
            print(f"\n  (no {SASCFG} yet — run without --show to create it)")
        return 0

    if not args.verify:
        if args.non_interactive:
            if args.viya:
                profile.mode, profile.viya_url = "viya", args.viya
            if args.host:
                profile.mode, profile.host = "iom", args.host
                profile.port = args.port
            if args.user:
                profile.user = args.user
            if args.table:
                profile.table = args.table
        else:
            profile = wizard(profile)

        missing = check_dependencies(profile.mode)
        if missing:
            print("\n  Missing prerequisites — the connection cannot work until "
                  "these are resolved:")
            for m in missing:
                print(f"    {m}")
            print("\n  Saving the profile anyway so it is ready afterwards.")

        save_profile(profile)
        if profile.mode == "iom":
            path = write_sascfg(profile)
            print(f"  saspy config      → {path}")
            print(f"  add to PYTHONPATH → {CONFIG_DIR}")
        if missing:
            return 1

    password = os.getenv("SAS_PASSWORD", "")
    # Only prompt when there is a terminal to prompt on: getpass blocks
    # forever under CI, a pipe, or nohup, which turns --verify into a hang.
    if (profile.mode == "iom" and not password and not args.non_interactive
            and sys.stdin.isatty()):
        try:
            password = getpass.getpass("  SAS password (not stored, blank to skip): ")
        except (EOFError, KeyboardInterrupt):
            password = ""
    elif profile.mode == "iom" and not password:
        print("  (no SAS_PASSWORD set and no terminal to prompt on — "
              "authentication will be attempted without one)")

    return verify(profile, password)


if __name__ == "__main__":
    raise SystemExit(main())
