#!/usr/bin/env python
"""Set up and verify a SAS connection, interactively.

The companion to ``sas_probe.py``: the probe *diagnoses* a connection, this one
*creates* it. It asks for what it needs, writes the config saspy expects,
verifies it end to end, and leaves behind a reusable profile.

    python scripts/sas_setup.py                 # interactive wizard
    python scripts/sas_setup.py --verify        # re-test the saved profile
    python scripts/sas_setup.py --show          # print the config it would use
    python scripts/sas_setup.py --non-interactive --host sas.corp --user me

Profiles live in ``~/.dqc/sas_profiles.json`` and the generated saspy config in
``~/.dqc/sascfg_personal.py``. Passwords are never written to either: they are
read from the ``SAS_PASSWORD`` environment variable or prompted for each run.
"""

from __future__ import annotations

import argparse
import getpass
import json
import os
import shutil
import stat
import subprocess
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

CONFIG_DIR = Path(os.getenv("DQC_SAS_HOME", Path.home() / ".dqc"))
PROFILES = CONFIG_DIR / "sas_profiles.json"
SASCFG = CONFIG_DIR / "sascfg_personal.py"


@dataclass
class Profile:
    name: str = "default"
    mode: str = "iom"                 # iom | viya
    host: str = ""
    port: int = 8591
    user: str = ""
    table: str = "mylib.ciclos_recuperacion"
    viya_url: str = ""
    java: str = ""
    classpath: str = ""
    encoding: str = "latin1"          # SAS 9.4 default on Windows/Linux deploys
    # Never stored: password, token.

    def to_dict(self) -> dict:
        return asdict(self)


# ── config I/O ────────────────────────────────────────────────────────────

def load_profiles() -> dict[str, dict]:
    if not PROFILES.exists():
        return {}
    try:
        return json.loads(PROFILES.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        print(f"  ! {PROFILES} is not valid JSON; ignoring it.", file=sys.stderr)
        return {}


def save_profile(profile: Profile) -> None:
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    data = load_profiles()
    data[profile.name] = profile.to_dict()
    PROFILES.write_text(json.dumps(data, indent=2), encoding="utf-8")
    PROFILES.chmod(stat.S_IRUSR | stat.S_IWUSR)     # 0600
    print(f"  profile '{profile.name}' → {PROFILES}")


def write_sascfg(profile: Profile) -> Path:
    """Generate the sascfg_personal.py saspy looks for.

    saspy is configured by a Python module, not a dotfile, which is why this
    is generated rather than templated into JSON.
    """
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    java = profile.java or shutil.which("java") or "java"
    cp = profile.classpath or "<path to sas.core.jar:sas.security.sspi.jar>"
    body = f'''"""Generated by scripts/sas_setup.py — edit the profile, not this file."""

SAS_config_names = ["{profile.name}"]

{profile.name} = {{
    "java": "{java}",
    "iomhost": "{profile.host}",
    "iomport": {profile.port},
    "encoding": "{profile.encoding}",
    "classpath": "{cp}",
}}
'''
    SASCFG.write_text(body, encoding="utf-8")
    SASCFG.chmod(stat.S_IRUSR | stat.S_IWUSR)
    return SASCFG


# ── checks ────────────────────────────────────────────────────────────────

def check_dependencies(mode: str) -> list[str]:
    """Missing prerequisites, as actionable install lines."""
    missing: list[str] = []
    if mode == "viya":
        try:
            import httpx  # noqa: F401
        except ImportError:
            missing.append("pip install httpx")
        return missing
    try:
        import saspy  # noqa: F401
    except ImportError:
        missing.append("pip install saspy")
    if not shutil.which("java"):
        missing.append("install a JRE (saspy's IOM access runs over Java) "
                       "— e.g. apt install default-jre")
    return missing


def find_sas_jars() -> list[str]:
    """Look for the SAS client jars saspy's IOM access needs.

    They ship with a SAS client installation and are not on PyPI, so if they
    are absent the connection cannot be made from this machine no matter what
    else is configured — worth finding out before prompting for a password.
    """
    wanted = ("sas.core.jar", "sas.security.sspi.jar", "sas.svc.connection.jar")
    roots = [Path("/opt/sas"), Path("/usr/local/SASHome"), Path("C:/Program Files/SASHome"),
             Path.home() / "sas"]
    found: list[str] = []
    for root in roots:
        if not root.exists():
            continue
        for name in wanted:
            for hit in root.rglob(name):
                found.append(str(hit))
                break
    return found


# ── wizard ────────────────────────────────────────────────────────────────

def ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    if not sys.stdin.isatty():          # piped or redirected: take the default
        return default
    try:
        answer = input(f"  {prompt}{suffix}: ").strip()
    except (EOFError, KeyboardInterrupt):
        return default
    return answer or default


def wizard(existing: Profile) -> Profile:
    print("\n── SAS connection setup ──────────────────────────────────────")
    print("  Nothing is sent until the end, and no password is written to disk.\n")

    mode = ask("Mode: (1) SAS 9.4 workspace server via IOM  (2) SAS Viya REST",
               "1" if existing.mode == "iom" else "2")
    p = Profile(name=existing.name, mode="viya" if mode.strip() == "2" else "iom")

    p.name = ask("Profile name", existing.name or "default")
    if p.mode == "viya":
        p.viya_url = ask("Viya base URL (https://...)", existing.viya_url)
    else:
        p.host = ask("Workspace server host", existing.host)
        p.port = int(ask("IOM port", str(existing.port or 8591)) or 8591)
        p.user = ask("User", existing.user or os.getenv("USER", ""))
        p.encoding = ask("SAS session encoding", existing.encoding or "latin1")

        jars = find_sas_jars()
        if jars:
            print(f"\n  Found SAS client jars:")
            for j in jars:
                print(f"    {j}")
            default_cp = ":".join(sorted({str(Path(j).parent) + "/*" for j in jars}))
        else:
            print("\n  ! No SAS client jars found in the usual locations.")
            print("    saspy's IOM access needs sas.core.jar and")
            print("    sas.security.sspi.jar from a SAS client installation.")
            print("    They are not on PyPI — ask whoever administers SAS.")
            default_cp = existing.classpath
        p.classpath = ask("Java classpath for the SAS jars", default_cp)

    p.table = ask("A table to test a 1-row SELECT against", existing.table)
    return p


# ── verification ──────────────────────────────────────────────────────────

def verify(profile: Profile, password: str = "") -> int:
    """Run sas_probe against this profile and report."""
    cmd = [sys.executable, str(Path(__file__).parent / "sas_probe.py"),
           "--table", profile.table]
    if profile.mode == "viya":
        cmd += ["--viya", profile.viya_url]
        token = os.getenv("SAS_TOKEN", "")
        if token:
            cmd += ["--token", token]
    else:
        cmd += ["--host", profile.host, "--port", str(profile.port)]
        if profile.user:
            cmd += ["--user", profile.user]
        if profile.name:
            cmd += ["--cfgname", profile.name]

    env = dict(os.environ)
    if password:
        env["SAS_PASSWORD"] = password
    if SASCFG.exists():
        # saspy imports sascfg_personal from sys.path
        env["PYTHONPATH"] = f"{CONFIG_DIR}{os.pathsep}{env.get('PYTHONPATH', '')}"

    print(f"\n  running: {' '.join(cmd[1:])}\n")
    return subprocess.call(cmd, env=env)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--profile", default="default")
    ap.add_argument("--verify", action="store_true",
                    help="re-test the saved profile without reconfiguring")
    ap.add_argument("--show", action="store_true",
                    help="print the saved profile and generated saspy config")
    ap.add_argument("--non-interactive", action="store_true")
    ap.add_argument("--host"); ap.add_argument("--port", type=int, default=8591)
    ap.add_argument("--user"); ap.add_argument("--viya"); ap.add_argument("--table")
    args = ap.parse_args()

    saved = load_profiles().get(args.profile, {})
    profile = Profile(**{**Profile(name=args.profile).to_dict(), **saved})

    if args.show:
        print(json.dumps(profile.to_dict(), indent=2))
        if SASCFG.exists():
            print(f"\n── {SASCFG} ──")
            print(SASCFG.read_text(encoding="utf-8"))
        else:
            print(f"\n  (no {SASCFG} yet — run without --show to create it)")
        return 0

    if not args.verify:
        if args.non_interactive:
            if args.viya:
                profile.mode, profile.viya_url = "viya", args.viya
            if args.host:
                profile.mode, profile.host = "iom", args.host
                profile.port = args.port
            if args.user:
                profile.user = args.user
            if args.table:
                profile.table = args.table
        else:
            profile = wizard(profile)

        missing = check_dependencies(profile.mode)
        if missing:
            print("\n  Missing prerequisites — the connection cannot work until "
                  "these are resolved:")
            for m in missing:
                print(f"    {m}")
            print("\n  Saving the profile anyway so it is ready afterwards.")

        save_profile(profile)
        if profile.mode == "iom":
            path = write_sascfg(profile)
            print(f"  saspy config      → {path}")
            print(f"  add to PYTHONPATH → {CONFIG_DIR}")
        if missing:
            return 1

    password = os.getenv("SAS_PASSWORD", "")
    # Only prompt when there is a terminal to prompt on: getpass blocks
    # forever under CI, a pipe, or nohup, which turns --verify into a hang.
    if (profile.mode == "iom" and not password and not args.non_interactive
            and sys.stdin.isatty()):
        try:
            password = getpass.getpass("  SAS password (not stored, blank to skip): ")
        except (EOFError, KeyboardInterrupt):
            password = ""
    elif profile.mode == "iom" and not password:
        print("  (no SAS_PASSWORD set and no terminal to prompt on — "
              "authentication will be attempted without one)")

    return verify(profile, password)


if __name__ == "__main__":
    raise SystemExit(main())
